# Generated by Django 6.0.2 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dj_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["holder_type", "holder_id"], name="wallet_holder_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "status", "created_at"],
                name="txn_wallet_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "type", "created_at"],
                name="txn_wallet_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["status", "created_at"], name="transfer_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(fields=["from_type", "from_id"], name="transfer_from_obj_idx"),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(fields=["to_type", "to_id"], name="transfer_to_obj_idx"),
        ),
    ]
