from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from django.contrib.auth.models import Group, Permission


@dataclass(frozen=True)
class RoleDefinition:
    label: str
    permissions: tuple[tuple[str, str], ...]


ROLE_DEFINITIONS: dict[str, RoleDefinition] = {
    "super_admin": RoleDefinition(
        label="Super Admin",
        permissions=(
            ("wallets_demo", "view_user"),
            ("wallets_demo", "add_user"),
            ("wallets_demo", "change_user"),
            ("wallets_demo", "delete_user"),
            ("auth", "view_group"),
            ("auth", "change_group"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "change_wallet"),
            ("dj_wallet", "view_transaction"),
            ("dj_wallet", "add_transaction"),
            ("dj_wallet", "change_transaction"),
            ("dj_wallet", "view_transfer"),
            ("dj_wallet", "add_transfer"),
            ("dj_wallet", "change_transfer"),
            ("wallets_demo", "view_approvalrequest"),
            ("wallets_demo", "add_approvalrequest"),
            ("wallets_demo", "change_approvalrequest"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "add_treasuryaccount"),
            ("wallets_demo", "change_treasuryaccount"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "add_treasurytransferrequest"),
            ("wallets_demo", "change_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "add_chartofaccount"),
            ("wallets_demo", "change_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "add_journalentry"),
            ("wallets_demo", "change_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "add_journalline"),
            ("wallets_demo", "change_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "add_fxrate"),
            ("wallets_demo", "change_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "add_merchant"),
            ("wallets_demo", "change_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "add_merchantloyaltyprogram"),
            ("wallets_demo", "change_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "add_merchantwalletcapability"),
            ("wallets_demo", "change_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "add_merchantloyaltyevent"),
            ("wallets_demo", "change_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "add_merchantcashflowevent"),
            ("wallets_demo", "change_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "add_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "change_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "add_customercif"),
            ("wallets_demo", "change_customercif"),
            ("wallets_demo", "delete_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "delete_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "add_merchantfeerule"),
            ("wallets_demo", "change_merchantfeerule"),
            ("wallets_demo", "delete_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "add_merchantriskprofile"),
            ("wallets_demo", "change_merchantriskprofile"),
            ("wallets_demo", "delete_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "add_merchantapicredential"),
            ("wallets_demo", "change_merchantapicredential"),
            ("wallets_demo", "delete_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
            ("wallets_demo", "add_merchantsettlementrecord"),
            ("wallets_demo", "change_merchantsettlementrecord"),
            ("wallets_demo", "delete_merchantsettlementrecord"),
        ),
    ),
    "admin": RoleDefinition(
        label="Admin",
        permissions=(
            ("wallets_demo", "view_user"),
            ("wallets_demo", "change_user"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("dj_wallet", "view_transfer"),
            ("wallets_demo", "view_approvalrequest"),
            ("wallets_demo", "change_approvalrequest"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "change_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "change_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "change_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "change_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "change_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "change_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "change_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "change_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "change_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "change_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "add_customercif"),
            ("wallets_demo", "change_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "add_merchantfeerule"),
            ("wallets_demo", "change_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "change_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "change_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
            ("wallets_demo", "add_merchantsettlementrecord"),
            ("wallets_demo", "change_merchantsettlementrecord"),
        ),
    ),
    "finance": RoleDefinition(
        label="Finance",
        permissions=(
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("dj_wallet", "add_transaction"),
            ("dj_wallet", "change_transaction"),
            ("dj_wallet", "view_transfer"),
            ("wallets_demo", "view_approvalrequest"),
            ("wallets_demo", "change_approvalrequest"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "add_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "add_chartofaccount"),
            ("wallets_demo", "change_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "add_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "add_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "add_fxrate"),
            ("wallets_demo", "change_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "add_merchant"),
            ("wallets_demo", "change_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "add_merchantloyaltyprogram"),
            ("wallets_demo", "change_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "add_merchantwalletcapability"),
            ("wallets_demo", "change_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "add_merchantloyaltyevent"),
            ("wallets_demo", "change_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "add_merchantcashflowevent"),
            ("wallets_demo", "change_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "add_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "change_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "add_merchantfeerule"),
            ("wallets_demo", "change_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "change_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "change_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
            ("wallets_demo", "add_merchantsettlementrecord"),
            ("wallets_demo", "change_merchantsettlementrecord"),
        ),
    ),
    "treasury": RoleDefinition(
        label="Treasury",
        permissions=(
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "add_treasurytransferrequest"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "add_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "add_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "add_fxrate"),
            ("wallets_demo", "change_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "add_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "add_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
        ),
    ),
    "customer_service": RoleDefinition(
        label="Customer Service",
        permissions=(
            ("wallets_demo", "view_user"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("dj_wallet", "view_transfer"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "add_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "add_customercif"),
            ("wallets_demo", "change_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "view_merchantsettlementrecord"),
        ),
    ),
    "risk": RoleDefinition(
        label="Risk",
        permissions=(
            ("wallets_demo", "view_user"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("dj_wallet", "view_transfer"),
            ("wallets_demo", "view_approvalrequest"),
            ("wallets_demo", "change_approvalrequest"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "change_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "change_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "change_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "change_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
            ("wallets_demo", "change_merchantsettlementrecord"),
        ),
    ),
    "operation": RoleDefinition(
        label="Operation",
        permissions=(
            ("wallets_demo", "view_user"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_treasurytransferrequest"),
            ("wallets_demo", "add_treasurytransferrequest"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "view_journalentry"),
            ("wallets_demo", "add_journalentry"),
            ("wallets_demo", "view_journalline"),
            ("wallets_demo", "add_journalline"),
            ("wallets_demo", "view_fxrate"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "add_merchant"),
            ("wallets_demo", "change_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "change_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "change_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "add_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "add_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "add_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "add_customercif"),
            ("wallets_demo", "change_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "change_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "add_merchantfeerule"),
            ("wallets_demo", "change_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "add_merchantriskprofile"),
            ("wallets_demo", "change_merchantriskprofile"),
            ("wallets_demo", "view_merchantapicredential"),
            ("wallets_demo", "add_merchantapicredential"),
            ("wallets_demo", "change_merchantapicredential"),
            ("wallets_demo", "view_merchantsettlementrecord"),
            ("wallets_demo", "add_merchantsettlementrecord"),
            ("wallets_demo", "change_merchantsettlementrecord"),
        ),
    ),
    "sales": RoleDefinition(
        label="Sales",
        permissions=(
            ("wallets_demo", "view_user"),
            ("dj_wallet", "view_wallet"),
            ("dj_wallet", "view_transaction"),
            ("wallets_demo", "view_treasuryaccount"),
            ("wallets_demo", "view_chartofaccount"),
            ("wallets_demo", "view_merchant"),
            ("wallets_demo", "view_merchantloyaltyprogram"),
            ("wallets_demo", "view_merchantwalletcapability"),
            ("wallets_demo", "view_merchantloyaltyevent"),
            ("wallets_demo", "add_merchantloyaltyevent"),
            ("wallets_demo", "view_merchantcashflowevent"),
            ("wallets_demo", "add_merchantcashflowevent"),
            ("wallets_demo", "view_operationcase"),
            ("wallets_demo", "add_operationcase"),
            ("wallets_demo", "change_operationcase"),
            ("wallets_demo", "view_operationcasenote"),
            ("wallets_demo", "add_operationcasenote"),
            ("wallets_demo", "view_customercif"),
            ("wallets_demo", "view_merchantkybrequest"),
            ("wallets_demo", "add_merchantkybrequest"),
            ("wallets_demo", "view_merchantfeerule"),
            ("wallets_demo", "view_merchantriskprofile"),
            ("wallets_demo", "view_merchantsettlementrecord"),
        ),
    ),
}

BACKOFFICE_ROLES: tuple[str, ...] = tuple(ROLE_DEFINITIONS.keys())
RBAC_ADMIN_ROLES: tuple[str, ...] = ("admin", "super_admin")
MAKER_ROLES: tuple[str, ...] = ("finance", "operation", "sales", "treasury")
CHECKER_ROLES: tuple[str, ...] = ("admin", "super_admin", "risk")
ACCOUNTING_ROLES: tuple[str, ...] = ("finance", "treasury", "admin", "super_admin")
ACCOUNTING_CHECKER_ROLES: tuple[str, ...] = ("admin", "super_admin", "risk")

DEFAULT_DEMO_ROLE_ASSIGNMENTS: dict[str, tuple[str, ...]] = {
    "admin": ("super_admin",),
    "alice": ("finance",),
    "bob": ("customer_service",),
    "charlie": ("risk", "treasury"),
}


def seed_role_groups() -> dict[str, list[str]]:
    missing_permissions: list[str] = []
    created_groups: list[str] = []
    updated_groups: list[str] = []

    for role_name, definition in ROLE_DEFINITIONS.items():
        group, created = Group.objects.get_or_create(name=role_name)
        permissions_to_set: list[Permission] = []
        for app_label, codename in definition.permissions:
            permission = Permission.objects.filter(
                content_type__app_label=app_label,
                codename=codename,
            ).first()
            if permission is None:
                missing_permissions.append(f"{app_label}.{codename}")
                continue
            permissions_to_set.append(permission)
        group.permissions.set(permissions_to_set)
        if created:
            created_groups.append(role_name)
        else:
            updated_groups.append(role_name)

    return {
        "created_groups": created_groups,
        "updated_groups": updated_groups,
        "missing_permissions": sorted(set(missing_permissions)),
    }


def assign_roles(user, roles: Iterable[str]) -> None:
    user.groups.clear()
    for role in roles:
        group = Group.objects.filter(name=role).first()
        if group is not None:
            user.groups.add(group)


def user_has_any_role(user, roles: Iterable[str]) -> bool:
    if not getattr(user, "is_authenticated", False):
        return False
    if getattr(user, "is_superuser", False):
        return True
    return user.groups.filter(name__in=list(roles)).exists()


def user_is_maker(user) -> bool:
    return user_has_any_role(user, MAKER_ROLES)


def user_is_checker(user) -> bool:
    return user_has_any_role(user, CHECKER_ROLES)
