from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('api/mobile/bootstrap/', views.mobile_bootstrap, name='mobile_bootstrap'),
    path('api/mobile/profile/', views.mobile_profile, name='mobile_profile'),
    path('api/mobile/statement/', views.mobile_statement, name='mobile_statement'),
    path('api/mobile/onboarding/self/', views.mobile_self_onboard, name='mobile_self_onboard'),
    path('metrics', views.metrics, name='metrics'),
    path('fx/exchange/', views.wallet_fx_exchange, name='wallet_fx_exchange'),
    path('backoffice/', views.backoffice, name='backoffice'),
    path('backoffice/audit/export/', views.backoffice_audit_export, name='backoffice_audit_export'),
    path('backoffice/rbac/', views.rbac_management, name='rbac_management'),
    path('backoffice/fx/', views.fx_management, name='fx_management'),
    path('backoffice/work-queue/', views.ops_work_queue, name='ops_work_queue'),
    path('backoffice/approval-matrix/', views.approval_matrix, name='approval_matrix'),
    path('backoffice/documents/', views.documents_center, name='documents_center'),
    path('backoffice/settlements/', views.settlement_operations, name='settlement_operations'),
    path('backoffice/reconciliation/', views.reconciliation_workbench, name='reconciliation_workbench'),
    path('backoffice/settings/', views.operations_settings, name='operations_settings'),
    path('backoffice/policy-hub/', views.policy_hub, name='policy_hub'),
    path('backoffice/operations/', views.operations_center, name='operations_center'),
    path('backoffice/cases/<int:case_id>/', views.case_detail, name='case_detail'),
    path('merchant/portal/', views.merchant_portal, name='merchant_portal'),
    path('backoffice/wallets/', views.wallet_management, name='wallet_management'),
    path('backoffice/accounting/', views.accounting_dashboard, name='accounting_dashboard'),
    path(
        'backoffice/accounting/entries/<int:entry_id>/post/',
        views.accounting_post_entry,
        name='accounting_post_entry',
    ),
    path('backoffice/treasury/', views.treasury_dashboard, name='treasury_dashboard'),
    path(
        'backoffice/treasury/<int:request_id>/decision/',
        views.treasury_decision,
        name='treasury_decision',
    ),
    path(
        'backoffice/approvals/<int:request_id>/decision/',
        views.approval_decision,
        name='approval_decision',
    ),
    path('deposit/', views.deposit, name='deposit'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('transfer/', views.transfer, name='transfer'),
    path('register/', views.register, name='register'),
    path('login/', views.portal_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('auth/keycloak/callback/', views.keycloak_callback, name='keycloak_callback'),
    path('logout/', views.portal_logout, name='logout'),
]
