# Generated by Django 6.0.2 on 2026-02-21 12:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0016_refund_payout_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantapicredential',
            name='scopes_csv',
            field=models.CharField(blank=True, default='wallet:read,payout:read,webhook:write', max_length=255),
        ),
        migrations.CreateModel(
            name='AccessReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_no', models.CharField(max_length=40, unique=True)),
                ('issue_type', models.CharField(default='segregation_of_duty', max_length=64)),
                ('details', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_access_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_review_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChargebackCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeback_no', models.CharField(max_length=40, unique=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('represented', 'Represented'), ('pre_arbitration', 'Pre-Arbitration'), ('won', 'Won'), ('lost', 'Lost'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('network_reference', models.CharField(blank=True, default='', max_length=64)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_chargeback_cases', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargebacks', to='wallets_demo.operationcase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_chargeback_cases', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargebacks', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargebacks', to='wallets_demo.merchant')),
                ('source_cashflow_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chargebacks', to='wallets_demo.merchantcashflowevent')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChargebackEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(default='receipt', max_length=64)),
                ('document_url', models.URLField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chargeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='wallets_demo.chargebackcase')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_chargeback_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='JournalBackdateApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('checker_note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_backdate_approvals', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backdate_approval', to='wallets_demo.journalentry')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_backdate_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SanctionScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='internal', max_length=64)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('score', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('potential_match', 'Potential Match'), ('confirmed_match', 'Confirmed Match')], db_index=True, default='clear', max_length=20)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_sanction_screenings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanction_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TransactionMonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='velocity', max_length=64)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_monitoring_alerts', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_alerts', to='wallets_demo.operationcase')),
                ('cashflow_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_alerts', to='wallets_demo.merchantcashflowevent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_monitoring_alerts', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_alerts', to='wallets_demo.merchant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_accounting_periods', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_accounting_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_start', '-id'),
                'unique_together': {('period_start', 'period_end', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='MerchantWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='callback', max_length=64)),
                ('nonce', models.CharField(db_index=True, max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('signature_valid', models.BooleanField(default=False)),
                ('replay_detected', models.BooleanField(default=False)),
                ('status', models.CharField(default='received', max_length=16)),
                ('response_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='wallets_demo.merchantapicredential')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'unique_together': {('credential', 'nonce')},
            },
        ),
    ]
