# Generated by Django 6.0.2 on 2026-02-21 16:20

import django.db.models.deletion
import wallets_demo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets_demo", "0017_merchantapicredential_scopes_csv_accessreviewrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("organization_name", models.CharField(default="DJ Wallet", max_length=128)),
                ("merchant_id_prefix", models.CharField(default="MCH", max_length=16)),
                ("wallet_id_prefix", models.CharField(default="WAL", max_length=16)),
                ("transaction_id_prefix", models.CharField(default="TXN", max_length=16)),
                ("service_transaction_prefixes", models.JSONField(blank=True, default=wallets_demo.models.default_service_transaction_prefixes)),
                ("cif_id_prefix", models.CharField(default="CIF", max_length=16)),
                ("journal_entry_prefix", models.CharField(default="JE", max_length=16)),
                ("case_no_prefix", models.CharField(default="CASE", max_length=16)),
                ("settlement_no_prefix", models.CharField(default="SETTLE", max_length=16)),
                ("payout_ref_prefix", models.CharField(default="PAYOUT", max_length=16)),
                ("recon_no_prefix", models.CharField(default="RECON", max_length=16)),
                ("chargeback_no_prefix", models.CharField(default="CB", max_length=16)),
                ("access_review_no_prefix", models.CharField(default="AR", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_operation_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operation setting",
                "verbose_name_plural": "Operation settings",
            },
        ),
    ]
