# Generated by Django 6.0.2 on 2026-02-22 06:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets_demo", "0019_operationsetting_enabled_currencies"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuryPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("single_txn_limit", models.DecimalField(decimal_places=2, default=Decimal("100000"), max_digits=20)),
                ("daily_outflow_limit", models.DecimalField(decimal_places=2, default=Decimal("1000000"), max_digits=20)),
                ("require_super_admin_above", models.DecimalField(decimal_places=2, default=Decimal("500000"), max_digits=20)),
                ("currency", models.CharField(default="USD", max_length=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_treasury_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Treasury policy",
                "verbose_name_plural": "Treasury policies",
            },
        ),
        migrations.AddField(
            model_name="treasurytransferrequest",
            name="required_checker_role",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="disputerefundrequest",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disputerefundrequest",
            name="escalation_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="disputerefundrequest",
            name="sla_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
