# Generated by Django 6.0.2 on 2026-02-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets_demo", "0020_treasurypolicy_and_workflow_controls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationsetting",
            options={"verbose_name": "System setting", "verbose_name_plural": "System settings"},
        ),
    ]
