# Generated by Django 5.2.7 on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0021_alter_operationsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('treasury_transfer', 'Treasury Transfer'), ('merchant_kyb', 'Merchant KYB'), ('dispute_refund', 'Dispute Refund'), ('settlement_payout', 'Settlement Payout'), ('journal_backdate', 'Journal Backdate')], db_index=True, max_length=32)),
                ('currency', models.CharField(blank=True, default='', help_text='Blank means all currencies', max_length=12)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('required_checker_role', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_approval_matrix_rules', to='wallets_demo.user')),
            ],
            options={
                'ordering': ('workflow_type', 'currency', 'min_amount', 'max_amount', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(choices=[('general', 'General'), ('case', 'Case'), ('kyb', 'KYB'), ('chargeback', 'Chargeback'), ('refund', 'Refund'), ('reconciliation', 'Reconciliation')], db_index=True, default='general', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(default='generic', max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='business_documents/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('is_internal', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wallets_demo.operationcase')),
                ('chargeback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wallets_demo.chargebackcase')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_documents', to='wallets_demo.user')),
                ('kyb_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wallets_demo.merchantkybrequest')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wallets_demo.merchant')),
                ('refund_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='wallets_demo.disputerefundrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_business_documents', to='wallets_demo.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
