# Generated by Django 5.2.7 on 2026-02-22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0022_approvalmatrixrule_businessdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatchFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=40, unique=True)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('settlement_count', models.PositiveIntegerField(default=0)),
                ('payout_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('approved', 'Approved'), ('uploaded', 'Uploaded'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='settlement_batches/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlement_batches', to='wallets_demo.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_batches', to='wallets_demo.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SettlementException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(default='unknown', max_length=64)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_settlement_exceptions', to='wallets_demo.user')),
                ('batch_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='wallets_demo.settlementbatchfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlement_exceptions', to='wallets_demo.user')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='wallets_demo.settlementpayout')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_settlement_exceptions', to='wallets_demo.user')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='wallets_demo.merchantsettlementrecord')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
