# Generated by Django 5.2.7 on 2026-02-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0023_settlementbatchfile_settlementexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationbreak',
            name='break_category',
            field=models.CharField(choices=[('amount_mismatch', 'Amount mismatch'), ('count_mismatch', 'Count mismatch'), ('missing_external', 'Missing external'), ('missing_internal', 'Missing internal'), ('duplicate', 'Duplicate'), ('timing_cutoff', 'Timing / cutoff'), ('reference_mismatch', 'Reference mismatch'), ('other', 'Other')], default='amount_mismatch', max_length=32),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='external_txn_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='internal_txn_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched')], db_index=True, default='unmatched', max_length=16),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='required_checker_role',
            field=models.CharField(blank=True, default='risk', max_length=32),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_reconciliation_break_resolutions', to='wallets_demo.user'),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_checker_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_request_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_reconciliation_break_resolutions', to='wallets_demo.user'),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='resolution_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=16),
        ),
        migrations.CreateModel(
            name='ReconciliationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(default='supporting_doc', max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='reconciliation_evidence/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recon_break', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='wallets_demo.reconciliationbreak')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_reconciliation_evidences', to='wallets_demo.user')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
