# Generated by Django 6.0.2 on 2026-02-22 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0024_reconciliation_workbench_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('post', 'Post Draft Entry'), ('reversal', 'Reversal'), ('reclass', 'Reclassification')], default='post', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('checker_note', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_journal_entry_approvals', to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='wallets_demo.journalentry')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_journal_entry_approvals', to=settings.AUTH_USER_MODEL)),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_approval_requests', to='wallets_demo.journalentry')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
