# Generated by Django 6.0.2 on 2026-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0025_journalentryapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationcase',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
