# Generated by Django 6.0.2 on 2026-02-22 10:45

import wallets_demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0026_operationcase_sla_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsetting',
            name='nav_visibility_rules',
            field=models.JSONField(blank=True, default=wallets_demo.models.default_nav_visibility_rules, help_text='Optional menu visibility overrides. Format: {"menu_key": ["role1", "role2"]}. Leave empty to use secure defaults.'),
        ),
        migrations.AddField(
            model_name='operationsetting',
            name='sensitive_data_roles',
            field=models.JSONField(blank=True, default=wallets_demo.models.default_sensitive_data_roles, help_text='Roles allowed to view sensitive amounts/balances. Leave empty to use secure defaults.'),
        ),
        migrations.AddField(
            model_name='operationsetting',
            name='sensitive_visibility_rules',
            field=models.JSONField(blank=True, default=wallets_demo.models.default_sensitive_visibility_rules, help_text='Optional sensitive-data visibility overrides by domain. Format: {"domain_key": ["role1", "role2"]}.'),
        ),
    ]
