# Generated by Django 6.0.2 on 2026-03-01 10:41

import django.db.models.deletion
from django.db import migrations, models
def backfill_workflow_tenants(apps, schema_editor):
    ApprovalRequest = apps.get_model("wallets_demo", "ApprovalRequest")
    TreasuryTransferRequest = apps.get_model("wallets_demo", "TreasuryTransferRequest")
    MerchantSettlementRecord = apps.get_model("wallets_demo", "MerchantSettlementRecord")
    DisputeRefundRequest = apps.get_model("wallets_demo", "DisputeRefundRequest")
    SettlementPayout = apps.get_model("wallets_demo", "SettlementPayout")
    SettlementBatchFile = apps.get_model("wallets_demo", "SettlementBatchFile")
    SettlementException = apps.get_model("wallets_demo", "SettlementException")
    ReconciliationRun = apps.get_model("wallets_demo", "ReconciliationRun")
    ReconciliationBreak = apps.get_model("wallets_demo", "ReconciliationBreak")
    BusinessDocument = apps.get_model("wallets_demo", "BusinessDocument")
    TransactionMonitoringAlert = apps.get_model("wallets_demo", "TransactionMonitoringAlert")
    AccessReviewRecord = apps.get_model("wallets_demo", "AccessReviewRecord")
    OperationCase = apps.get_model("wallets_demo", "OperationCase")
    OperationCaseNote = apps.get_model("wallets_demo", "OperationCaseNote")
    CustomerClassUpgradeRequest = apps.get_model("wallets_demo", "CustomerClassUpgradeRequest")

    def infer(*values):
        for value in values:
            if value:
                return value
        return None

    def backfill(model, rels, batch=500):
        pending = []
        for row in model.objects.filter(tenant__isnull=True).select_related(*rels).iterator(chunk_size=batch):
            tenant_id = None
            if model is ApprovalRequest:
                tenant_id = infer(
                    getattr(row.source_user, "tenant_id", None),
                    getattr(row.maker, "tenant_id", None),
                    getattr(getattr(row, "recipient_user", None), "tenant_id", None),
                )
            elif model is TreasuryTransferRequest:
                tenant_id = infer(
                    getattr(row.maker, "tenant_id", None),
                    getattr(getattr(row, "checker", None), "tenant_id", None),
                )
            elif model is MerchantSettlementRecord:
                tenant_id = infer(
                    getattr(row.merchant, "tenant_id", None),
                    getattr(row.created_by, "tenant_id", None),
                )
            elif model is DisputeRefundRequest:
                tenant_id = infer(
                    getattr(row.merchant, "tenant_id", None),
                    getattr(row.customer, "tenant_id", None),
                    getattr(row.maker, "tenant_id", None),
                    getattr(getattr(row, "case", None), "tenant_id", None),
                )
            elif model is SettlementPayout:
                tenant_id = infer(
                    getattr(getattr(row, "settlement", None), "tenant_id", None),
                    getattr(getattr(getattr(row, "settlement", None), "merchant", None), "tenant_id", None),
                )
            elif model is SettlementBatchFile:
                tenant_id = infer(
                    getattr(row.created_by, "tenant_id", None),
                    getattr(getattr(row, "approved_by", None), "tenant_id", None),
                )
            elif model is SettlementException:
                tenant_id = infer(
                    getattr(getattr(row, "settlement", None), "tenant_id", None),
                    getattr(getattr(row, "payout", None), "tenant_id", None),
                    getattr(row.created_by, "tenant_id", None),
                )
            elif model is ReconciliationRun:
                tenant_id = getattr(row.created_by, "tenant_id", None)
            elif model is ReconciliationBreak:
                tenant_id = infer(
                    getattr(getattr(row, "run", None), "tenant_id", None),
                    getattr(getattr(row, "merchant", None), "tenant_id", None),
                    getattr(row.created_by, "tenant_id", None),
                )
            elif model is BusinessDocument:
                tenant_id = infer(
                    getattr(getattr(row, "case", None), "tenant_id", None),
                    getattr(getattr(row, "merchant", None), "tenant_id", None),
                    getattr(getattr(row, "customer", None), "tenant_id", None),
                    getattr(row.uploaded_by, "tenant_id", None),
                )
            elif model is TransactionMonitoringAlert:
                tenant_id = infer(
                    getattr(getattr(row, "case", None), "tenant_id", None),
                    getattr(getattr(row, "merchant", None), "tenant_id", None),
                    getattr(getattr(row, "user", None), "tenant_id", None),
                    getattr(getattr(row, "created_by", None), "tenant_id", None),
                )
            elif model is AccessReviewRecord:
                tenant_id = infer(
                    getattr(row.user, "tenant_id", None),
                    getattr(getattr(row, "reviewer", None), "tenant_id", None),
                )
            elif model is OperationCase:
                tenant_id = infer(
                    getattr(row.customer, "tenant_id", None),
                    getattr(getattr(row, "merchant", None), "tenant_id", None),
                    getattr(row.created_by, "tenant_id", None),
                )
            elif model is OperationCaseNote:
                tenant_id = infer(
                    getattr(getattr(row, "case", None), "tenant_id", None),
                    getattr(row.created_by, "tenant_id", None),
                )
            elif model is CustomerClassUpgradeRequest:
                tenant_id = infer(
                    getattr(getattr(row, "cif", None), "tenant_id", None),
                    getattr(row.maker, "tenant_id", None),
                )
            if tenant_id:
                row.tenant_id = tenant_id
                pending.append(row)
                if len(pending) >= batch:
                    model.objects.bulk_update(pending, ["tenant"])
                    pending = []
        if pending:
            model.objects.bulk_update(pending, ["tenant"])

    backfill(ApprovalRequest, ("source_user", "maker", "recipient_user"))
    backfill(TreasuryTransferRequest, ("maker", "checker"))
    backfill(MerchantSettlementRecord, ("merchant", "created_by"))
    backfill(DisputeRefundRequest, ("merchant", "customer", "maker", "case"))
    backfill(SettlementPayout, ("settlement", "settlement__merchant"))
    backfill(SettlementBatchFile, ("created_by", "approved_by"))
    backfill(SettlementException, ("settlement", "payout", "created_by"))
    backfill(ReconciliationRun, ("created_by",))
    backfill(ReconciliationBreak, ("run", "merchant", "created_by"))
    backfill(BusinessDocument, ("case", "merchant", "customer", "uploaded_by"))
    backfill(TransactionMonitoringAlert, ("case", "merchant", "user", "created_by"))
    backfill(AccessReviewRecord, ("user", "reviewer"))
    backfill(OperationCase, ("customer", "merchant", "created_by"))
    backfill(OperationCaseNote, ("case", "created_by"))
    backfill(CustomerClassUpgradeRequest, ("cif", "maker"))


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0034_merchant_api_credential_environments'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessreviewrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_review_records', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='businessdocument',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_documents', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='customerclassupgraderequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_class_upgrade_requests', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='disputerefundrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_refund_requests', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='merchantsettlementrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_settlement_records', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='operationcase',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_cases', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='operationcasenote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_case_notes', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_breaks', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='settlementbatchfile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batch_files', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='settlementexception',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_exceptions', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='settlementpayout',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_payouts', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='transactionmonitoringalert',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_monitoring_alerts', to='wallets_demo.tenant'),
        ),
        migrations.AddField(
            model_name='treasurytransferrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transfer_requests', to='wallets_demo.tenant'),
        ),
        migrations.AlterField(
            model_name='customercif',
            name='status',
            field=models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('active', 'Active'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='active', max_length=16),
        ),
        migrations.RunPython(backfill_workflow_tenants, noop_reverse),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_bdoc_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='operationcase',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_case_tenant_status_created'),
        ),
        migrations.AddIndex(
            model_name='reconciliationbreak',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_rbreak_tenant_stat_created'),
        ),
        migrations.AddIndex(
            model_name='settlementpayout',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_payout_tenant_stat_created'),
        ),
        migrations.AddIndex(
            model_name='transactionmonitoringalert',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_alert_tenant_stat_created'),
        ),
    ]
