# Generated by Django 6.0.2 on 2026-03-01 10:51

import django.db.models.deletion
from django.db import migrations, models


def assert_no_null_workflow_tenants(apps, schema_editor):
    targets = [
        ("ApprovalRequest", "approvalrequest"),
        ("TreasuryTransferRequest", "treasurytransferrequest"),
        ("MerchantSettlementRecord", "merchantsettlementrecord"),
        ("DisputeRefundRequest", "disputerefundrequest"),
        ("SettlementPayout", "settlementpayout"),
        ("SettlementBatchFile", "settlementbatchfile"),
        ("SettlementException", "settlementexception"),
        ("ReconciliationRun", "reconciliationrun"),
        ("ReconciliationBreak", "reconciliationbreak"),
        ("BusinessDocument", "businessdocument"),
        ("TransactionMonitoringAlert", "transactionmonitoringalert"),
        ("AccessReviewRecord", "accessreviewrecord"),
        ("OperationCase", "operationcase"),
        ("OperationCaseNote", "operationcasenote"),
        ("CustomerClassUpgradeRequest", "customerclassupgraderequest"),
    ]
    missing_counts = {}
    for model_name, label in targets:
        model = apps.get_model("wallets_demo", model_name)
        count = model.objects.filter(tenant__isnull=True).count()
        if count:
            missing_counts[label] = count
    if missing_counts:
        details = ", ".join(
            f"{name}={count}" for name, count in sorted(missing_counts.items())
        )
        raise RuntimeError(
            "Cannot enforce non-null tenant ownership. Rows missing tenant: "
            f"{details}. Backfill these rows first."
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        (
            "wallets_demo",
            "0035_accessreviewrecord_tenant_approvalrequest_tenant_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(assert_no_null_workflow_tenants, noop_reverse),
        migrations.AlterField(
            model_name="accessreviewrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_review_records",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="businessdocument",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_documents",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="customerclassupgraderequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_class_upgrade_requests",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="disputerefundrequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispute_refund_requests",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="merchantsettlementrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merchant_settlement_records",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="operationcase",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_cases",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="operationcasenote",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operation_case_notes",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationbreak",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation_breaks",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reconciliation_runs",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="settlementbatchfile",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlement_batch_files",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="settlementexception",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlement_exceptions",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="settlementpayout",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlement_payouts",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="transactionmonitoringalert",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction_monitoring_alerts",
                to="wallets_demo.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="treasurytransferrequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treasury_transfer_requests",
                to="wallets_demo.tenant",
            ),
        ),
    ]
