# Generated by Django 6.0.2 on 2026-03-01 11:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0036_enforce_workflow_tenant_non_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBillingWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField()),
                ('signing_secret', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_webhook', to='wallets_demo.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_tenant_billing_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tenant__code',),
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(default='starter', max_length=32)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], db_index=True, default='trial', max_length=16)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('monthly_base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('per_txn_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('included_txn_quota', models.PositiveIntegerField(default=0)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='wallets_demo.tenant')),
            ],
            options={
                'ordering': ('tenant__code',),
            },
        ),
        migrations.CreateModel(
            name='TenantBillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='wallets_demo.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='idx_tbill_tenant_stat_created'), models.Index(fields=['status', 'next_retry_at'], name='idx_tbill_status_retry')],
            },
        ),
        migrations.CreateModel(
            name='TenantUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True)),
                ('metric_code', models.CharField(db_index=True, max_length=48)),
                ('quantity', models.BigIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_daily', to='wallets_demo.tenant')),
            ],
            options={
                'ordering': ('-usage_date', 'metric_code'),
                'indexes': [models.Index(fields=['tenant', '-usage_date', 'metric_code'], name='idx_tusage_tenant_day_metric')],
                'unique_together': {('tenant', 'usage_date', 'metric_code')},
            },
        ),
    ]
