# Generated by Django 6.0.2 on 2026-03-01 11:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets_demo', '0037_tenantbillingwebhook_tenantsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='hard_limit_enforced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='hard_limit_monthly_txn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='plan_features_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TenantBillingInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_inbound_events', to='wallets_demo.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='idx_tinbound_tenant_created')],
                'unique_together': {('tenant', 'external_event_id')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=48, unique=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('currency', models.CharField(default='USD', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=16)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('line_items_json', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='wallets_demo.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='idx_tinv_tenant_stat_created')],
                'unique_together': {('tenant', 'period_start', 'period_end')},
            },
        ),
    ]
